version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superstrongpassword123
      MYSQL_DATABASE: product_catalog
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
